# Generated by Django 3.1.7 on 2021-03-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tilte',
            new_name='title',
        ),
    ]
