# Generated by Django 3.1.7 on 2021-04-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_user',
            new_name='comment_author',
        ),
    ]
