# Generated by Django 3.1.7 on 2021-04-06 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20210406_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
